name = "LearnControlSystems"
uuid = "21885a31-17d9-44da-a92e-98f71c6a736c"
authors = ["nop <noplab90@gmail.com>"]
version = "0.1.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"

[compat]
ControlSystems = "1.15.1"
